// @flow

export const LOGIN = 'LOGIN';

export const GET_COACHES_REQUEST = 'GET_COACHES_REQUEST';
export const GET_COACHES_SUCCESS = 'GET_COACHES_SUCCESS';
export const GET_COACHES_FAILURE = 'GET_COACHES_FAILURE';

export const GET_PLAYERS_REQUEST = 'GET_PLAYERS_REQUEST';
export const GET_PLAYERS_SUCCESS = 'GET_PLAYERS_SUCCESS';
export const GET_PLAYERS_FAILURE = 'GET_PLAYERS_FAILURE';

export const GET_TOURNAMENTS_REQUEST = 'GET_TOURNAMENTS_REQUEST';
export const GET_TOURNAMENTS_SUCCESS = 'GET_TOURNAMENTS_SUCCESS';
export const GET_TOURNAMENTS_FAILURE = 'GET_TOURNAMENTS_FAILURE';

export const GET_POINTS_REQUEST = 'GET_POINTS_REQUEST';
export const GET_POINTS_SUCCESS = 'GET_POINTS_SUCCESS';
export const GET_POINTS_FAILURE = 'GET_POINTS_FAILURE';

export const GET_SCHEDULE_REQUEST = 'GET_SCHEDULE_REQUEST';
export const GET_SCHEDULE_SUCCESS = 'GET_SCHEDULE_SUCCESS';
export const GET_SCHEDULE_FAILURE = 'GET_SCHEDULE_FAILURE';

export const EDIT_PLAYER_REQUEST = 'EDIT_PLAYER_REQUEST';
export const EDIT_PLAYER_SUCCESS = 'EDIT_PLAYER_SUCCESS';
export const EDIT_PLAYER_FAILURE = 'EDIT_PLAYER_FAILURE';

export const ADD_PLAYER_REQUEST = 'ADD_PLAYER_REQUEST';
export const ADD_PLAYER_SUCCESS = 'ADD_PLAYER_SUCCESS';
export const ADD_PLAYER_FAILURE = 'ADD_PLAYER_FAILURE';

export const REMOVE_PLAYER_REQUEST = 'REMOVE_PLAYER_REQUEST';
export const REMOVE_PLAYER_SUCCESS = 'REMOVE_PLAYER_SUCCESS';
export const REMOVE_PLAYER_FAILURE = 'REMOVE_PLAYER_FAILURE';

export const EDIT_COACH_REQUEST = 'EDIT_COACH_REQUEST';
export const EDIT_COACH_SUCCESS = 'EDIT_COACH_SUCCESS';
export const EDIT_COACH_FAILURE = 'EDIT_COACH_FAILURE';

export const ADD_COACH_REQUEST = 'ADD_COACH_REQUEST';
export const ADD_COACH_SUCCESS = 'ADD_COACH_SUCCESS';
export const ADD_COACH_FAILURE = 'ADD_COACH_FAILURE';

export const REMOVE_COACH_REQUEST = 'REMOVE_COACH_REQUEST';
export const REMOVE_COACH_SUCCESS = 'REMOVE_COACH_SUCCESS';
export const REMOVE_COACH_FAILURE = 'REMOVE_COACH_FAILURE';

export const EDIT_TOUR_REQUEST = 'EDIT_TOUR_REQUEST';
export const EDIT_TOUR_SUCCESS = 'EDIT_TOUR_SUCCESS';
export const EDIT_TOUR_FAILURE = 'EDIT_TOUR_FAILURE';

export const ADD_TOUR_REQUEST = 'ADD_TOUR_REQUEST';
export const ADD_TOUR_SUCCESS = 'ADD_TOUR_SUCCESS';
export const ADD_TOUR_FAILURE = 'ADD_TOUR_FAILURE';

export const REMOVE_TOUR_REQUEST = 'REMOVE_TOUR_REQUEST';
export const REMOVE_TOUR_SUCCESS = 'REMOVE_TOUR_SUCCESS';
export const REMOVE_TOUR_FAILURE = 'REMOVE_TOUR_FAILURE';

export const GET_NEWS_CHILDREN_REQUEST = 'GET_NEWS_CHILDREN_REQUEST';
export const GET_NEWS_CHILDREN_SUCCESS = 'GET_NEWS_CHILDREN_SUCCESS';
export const GET_NEWS_CHILDREN_FAILURE = 'GET_NEWS_CHILDREN_FAILURE';

export const EDIT_ONE_NEW_REQUEST = 'EDIT_ONE_NEW_REQUEST';
export const EDIT_ONE_NEW_SUCCESS = 'EDIT_ONE_NEW_SUCCESS';
export const EDIT_ONE_NEW_FAILURE = 'EDIT_ONE_NEW_FAILURE';

export const ADD_ONE_NEW_REQUEST = 'ADD_ONE_NEW_REQUEST';
export const ADD_ONE_NEW_SUCCESS = 'ADD_ONE_NEW_SUCCESS';
export const ADD_ONE_NEW_FAILURE = 'ADD_ONE_NEW_FAILURE';

export const REMOVE_ONE_NEW_REQUEST = 'REMOVE_ONE_NEW_REQUEST';
export const REMOVE_ONE_NEW_SUCCESS = 'REMOVE_ONE_NEW_SUCCESS';
export const REMOVE_ONE_NEW_FAILURE = 'REMOVE_ONE_NEW_FAILURE';
