// @flow

export const GET_COACHES_REQUEST = 'GET_COACHES_REQUEST';
export const GET_COACHES_SUCCESS = 'GET_COACHES_SUCCESS';
export const GET_COACHES_FAILURE = 'GET_COACHES_FAILURE';

export const GET_PLAYERS_REQUEST = 'GET_PLAYERS_REQUEST';
export const GET_PLAYERS_SUCCESS = 'GET_PLAYERS_SUCCESS';
export const GET_PLAYERS_FAILURE = 'GET_PLAYERS_FAILURE';

export const GET_TOURNAMENTS_REQUEST = 'GET_TOURNAMENTS_REQUEST';
export const GET_TOURNAMENTS_SUCCESS = 'GET_TOURNAMENTS_SUCCESS';
export const GET_TOURNAMENTS_FAILURE = 'GET_TOURNAMENTS_FAILURE';

export const GET_POINTS_REQUEST = 'GET_POINTS_REQUEST';
export const GET_POINTS_SUCCESS = 'GET_POINTS_SUCCESS';
export const GET_POINTS_FAILURE = 'GET_POINTS_FAILURE';

export const GET_SCHEDULE_REQUEST = 'GET_SCHEDULE_REQUEST';
export const GET_SCHEDULE_SUCCESS = 'GET_SCHEDULE_SUCCESS';
export const GET_SCHEDULE_FAILURE = 'GET_SCHEDULE_FAILURE';

export const EDIT_PLAYER_REQUEST = 'EDIT_PLAYER_REQUEST';
export const EDIT_PLAYER_SUCCESS = 'EDIT_PLAYER_SUCCESS';
export const EDIT_PLAYER_FAILURE = 'EDIT_PLAYER_FAILURE';

export const ADD_PLAYER_REQUEST = 'ADD_PLAYER_REQUEST';
export const ADD_PLAYER_SUCCESS = 'ADD_PLAYER_SUCCESS';
export const ADD_PLAYER_FAILURE = 'ADD_PLAYER_FAILURE';

export const REMOVE_PLAYER_REQUEST = 'REMOVE_PLAYER_REQUEST';
export const REMOVE_PLAYER_SUCCESS = 'REMOVE_PLAYER_SUCCESS';
export const REMOVE_PLAYER_FAILURE = 'REMOVE_PLAYER_FAILURE';
