// @flow

export const GET_DATA_RATING = 'GET_DATA_RATING';
export const GET_CALENDAR_DATA_REQUEST = 'GET_CALENDAR_DATA_REQUEST';
export const GET_CALENDAR_DATA_SUCCESS = 'GET_CALENDAR_DATA_SUCCESS';
export const GET_CALENDAR_DATA_FAILURE = 'GET_CALENDAR_DATA_FAILURE';
export const SET_DATA_RATING_IS_LOADING = 'SET_DATA_RATING_IS_LOADING';
export const UNSET_DATA_RATING_IS_LOADING = 'UNSET_DATA_RATING_IS_LOADING';
